[project]
name = "email-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.3.14",
    "langchain-openai>=1.4.1",
    "langgraph>=1.2.10",
    "langsmith>=0.10.15",
    "pyobjc-framework-eventkit>=12.2.1",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = ["pyright>=1.1.411", "pytest>=9.1.1", "pytest-cov>=7.1.0", "ruff>=0.16.1"]

[project.scripts]
email-agent = "email_agent.main:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13"]
build-backend = "uv_build"
